### ISSUE TITLE
lambda-deploy.exe deploy not working

### ISSUE THREAD

**Issue by fintan63** [m0ngr31/kodi-alexa#145]
Hi 

When I try to deploy to AWS, I get the error below. In .env file I have

AWS_DEFAULT_REGION = eu-west-1

What am I doing wrong?
Thanks

`C:\temp\kodi-alexa-master>c:\Python27\Scripts\lambda-deploy.exe deploy
2017-04-11 15:44:11:INFO:botocore.vendored.requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): 169.254.169.254
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\Python27\Scripts\lambda-deploy.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\lambda_deploy\lambda_deploy.py", line 360, in main
    name=options.name
  File "c:\python27\lib\site-packages\lambda_deploy\lambda_deploy.py", line 75, in __init__
    self.client = boto3.client('lambda')
  File "c:\python27\lib\site-packages\boto3\__init__.py", line 83, in client
    return _get_default_session().client(*args, **kwargs)
  File "c:\python27\lib\site-packages\boto3\session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "c:\python27\lib\site-packages\botocore\session.py", line 836, in create_client
    client_config=config, api_version=api_version)
  File "c:\python27\lib\site-packages\botocore\client.py", line 70, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "c:\python27\lib\site-packages\botocore\client.py", line 224, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "c:\python27\lib\site-packages\botocore\args.py", line 45, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "c:\python27\lib\site-packages\botocore\args.py", line 103, in compute_client_args
    service_name, region_name, endpoint_url, is_secure)
  File "c:\python27\lib\site-packages\botocore\client.py", line 297, in resolve
    service_name, region_name)
  File "c:\python27\lib\site-packages\botocore\regions.py", line 122, in construct_endpoint
    partition, service_name, region_name)
  File "c:\python27\lib\site-packages\botocore\regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.

C:\temp\kodi-alexa-master>`
C:\temp\kodi-alexa-master>c:\Python27\Scripts\lambda-deploy.exe deploy
2017-04-11 15:44:11:INFO:botocore.vendored.requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): 169.254.169.254
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\Python27\Scripts\lambda-deploy.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\lambda_deploy\lambda_deploy.py", line 360, in main
    name=options.name
  File "c:\python27\lib\site-packages\lambda_deploy\lambda_deploy.py", line 75, in __init__
    self.client = boto3.client('lambda')
  File "c:\python27\lib\site-packages\boto3\__init__.py", line 83, in client
    return _get_default_session().client(*args, **kwargs)
  File "c:\python27\lib\site-packages\boto3\session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "c:\python27\lib\site-packages\botocore\session.py", line 836, in create_client
    client_config=config, api_version=api_version)
  File "c:\python27\lib\site-packages\botocore\client.py", line 70, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "c:\python27\lib\site-packages\botocore\client.py", line 224, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "c:\python27\lib\site-packages\botocore\args.py", line 45, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "c:\python27\lib\site-packages\botocore\args.py", line 103, in compute_client_args
    service_name, region_name, endpoint_url, is_secure)
  File "c:\python27\lib\site-packages\botocore\client.py", line 297, in resolve
    service_name, region_name)
  File "c:\python27\lib\site-packages\botocore\regions.py", line 122, in construct_endpoint
    partition, service_name, region_name)
  File "c:\python27\lib\site-packages\botocore\regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.

C:\temp\kodi-alexa-master>
```

**Comment by jingai** [comment]
As the [README states](https://github.com/m0ngr31/kodi-alexa/blob/master/README.md#getting-help), please post support requests on the forum.
