### ISSUE TITLE
little feedback for 2.6.2

### ISSUE THREAD

**Issue by mcl22** [m0ngr31/kodi-alexa#178]
I still do get errors when trying to switch the audio stream (language) or the subtitles. It works actually but Alexa's response indicates an error and the log shows:
Wechsel zum n\xc3\xa4chsten Audio Stream
 Sending request to http://***/jsonrpc from device amzn1.ask.device.AH***
 Sending request to http://***/jsonrpc from device amzn1.ask.device.AH***
 [2017-05-29 08:32:19,782] ERROR in app: Exception on / [POST]
 Traceback (most recent call last):
   File "C:\\Python27\\lib\\site-packages\\flask\\app.py", line 1982, in wsgi_app
     response = self.full_dispatch_request()
   File "C:\\Python27\\lib\\site-packages\\flask\\app.py", line 1614, in full_dispatch_request
     rv = self.handle_user_exception(e)
   File "C:\\Python27\\lib\\site-packages\\flask\\app.py", line 1517, in handle_user_exception
     reraise(exc_type, exc_value, tb)
   File "C:\\Python27\\lib\\site-packages\\flask\\app.py", line 1612, in full_dispatch_request
     rv = self.dispatch_request()
   File "C:\\Python27\\lib\\site-packages\\flask\\app.py", line 1598, in dispatch_request
     return self.view_functions[rule.endpoint](**req.view_args)
   File "C:\\Python27\\lib\\site-packages\\flask_ask\\core.py", line 594, in _flask_view_func
     result = self._map_intent_to_view_func(self.request.intent)()
   File "C:/***/htdocs/kodi-alexa\\alexa.py", line 1115, in alexa_audiostream_next
     response_text = kodi.GetCurrentAudioStream()
   File "C:\\Python27\\lib\\site-packages\\kodi_voice\\kodi.py", line 1271, in GetCurrentAudioStream
     country_dic = getisocodes_dict()
   File "C:\\Python27\\lib\\site-packages\\kodi_voice\\kodi.py", line 207, in getisocodes_dict
     f = codecs.open(country_dic_file, 'rb', 'utf-8')
   File "C:\\Python27\\Lib\\codecs.py", line 896, in open
     file = __builtin__.open(filename, mode, buffering)
 IOError: [Errno 2] No such file or directory: 'C:\\\\Python27\\\\lib\\\\site-packages\\\\kodi_voice\\\\ISO-639-2_utf-8.txt'

Of course I updated to the newest version of kodi-voice before. Nevertheless I tried a pip install --upgrade kodi-voice. But also after doing that the textfile was not in the folder as I would have supposed. So I manually downloaded it from github and saved it in the folder.
But after that the log told me this:
 Wechsel zum n\xc3\xa4chsten Audio Stream
 Sending request to http://***/jsonrpc from device amzn1.ask.device.AH***
 Sending request to http://***/jsonrpc from device amzn1.ask.device.AH***
 ERROR in app: Exception on / [POST]
 Traceback (most recent call last):
   File "C:\\Python27\\lib\\site-packages\\flask\\app.py", line 1982, in wsgi_app
     response = self.full_dispatch_request()
   File "C:\\Python27\\lib\\site-packages\\flask\\app.py", line 1614, in full_dispatch_request
     rv = self.handle_user_exception(e)
   File "C:\\Python27\\lib\\site-packages\\flask\\app.py", line 1517, in handle_user_exception
     reraise(exc_type, exc_value, tb)
   File "C:\\Python27\\lib\\site-packages\\flask\\app.py", line 1612, in full_dispatch_request
     rv = self.dispatch_request()
   File "C:\\Python27\\lib\\site-packages\\flask\\app.py", line 1598, in dispatch_request
     return self.view_functions[rule.endpoint](**req.view_args)
   File "C:\\Python27\\lib\\site-packages\\flask_ask\\core.py", line 594, in _flask_view_func
     result = self._map_intent_to_view_func(self.request.intent)()
   File "C:/***/htdocs/kodi-alexa\\alexa.py", line 1115, in alexa_audiostream_next
     response_text = kodi.GetCurrentAudioStream()
   File "C:\\Python27\\lib\\site-packages\\kodi_voice\\kodi.py", line 1271, in GetCurrentAudioStream
     country_dic = getisocodes_dict()
   File "C:\\Python27\\lib\\site-packages\\kodi_voice\\kodi.py", line 210, in getisocodes_dict
     iD['bibliographic'], iD['terminologic'], iD['alpha2'], iD['english'], iD['french'] = line.encode("utf-8").strip().split('|')
 ValueError: need more than 1 value to unpack

Second thing, I know it was my suggestion to include all artists in the search process. But I know recognize a lot of timeouts. I guess that's because of the much bigger list of artits. Between "searching for artist" (sending request) and "simple match ..." are 8 to 10 seconds for me. Perhaps it's not the fastest pc I do have there but it's at least an i3 and the cpu load doesn't max. So it's really the bigger list I guess.

I guess I can change it back by editing
def GetMusicArtists(self):
    return self.SendCommand(RPCString("AudioLibrary.GetArtists", {"albumartistsonly": False}))
in kodi-voice. Just wanted to mention it because I could imagine that others run into this "problem", too.

Finally for WhatNewMovies I still get an error when asking for "Komödie":
Sending request to http://***/jsonrpc from device amzn1.ask.device.AH***
 Trying to match: komodie
 Simple match failed, trying fuzzy match...
 Trying to match komodie from <function digits2roman at 0x0360A530>
 Fuzzy match 92%
 Neu hinzugef\xc3\xbcgte kom\xc3\xb6die Filme
 Sending request to http://127.0.0.1:8081/jsonrpc from device amzn1.ask.device.AH***
 [2017-05-29 11:45:35,780] ERROR in app: Exception on / [POST]
 Traceback (most recent call last):
   File "C:\\Python27\\lib\\site-packages\\flask\\app.py", line 1982, in wsgi_app
     response = self.full_dispatch_request()
   File "C:\\Python27\\lib\\site-packages\\flask\\app.py", line 1614, in full_dispatch_request
     rv = self.handle_user_exception(e)
   File "C:\\Python27\\lib\\site-packages\\flask\\app.py", line 1517, in handle_user_exception
     reraise(exc_type, exc_value, tb)
   File "C:\\Python27\\lib\\site-packages\\flask\\app.py", line 1612, in full_dispatch_request
     rv = self.dispatch_request()
   File "C:\\Python27\\lib\\site-packages\\flask\\app.py", line 1598, in dispatch_request
     return self.view_functions[rule.endpoint](**req.view_args)
   File "C:\\Python27\\lib\\site-packages\\flask_ask\\core.py", line 594, in _flask_view_func
     result = self._map_intent_to_view_func(self.request.intent)()
   File "C:/***/htdocs/kodi-alexa\\alexa.py", line 2091, in alexa_what_new_movies
     new_movies = kodi.GetUnwatchedMoviesByGenre(genre_located['label'])
   File "C:\\Python27\\lib\\site-packages\\kodi_voice\\kodi.py", line 1117, in GetUnwatchedMoviesByGenre
     for d in data['result']['movies']:
 KeyError: 'movies'

**Comment by jingai** [comment]
I simply forgot to include the dictionary in the manifest.  It's fixed in Kodi-Voice 0.8.2.

However, your problem with subtitles and audio streams now is #126.  We need someone to add a 6th column in the dictionary file with German translations.

I can make the option to include song artists configurable.

Your issue with `Komödie` is related to #172 most likely.

Going to close this and add a new Issue for just the option to include song artists configurable.

**Comment by jingai** [comment]
The song artists thing will be tracked over at kodi-voice/issues/5
