### ISSUE TITLE
Uncaught Exception After Deploy From Zappa

### ISSUE THREAD

**Issue by jpgamboa** [m0ngr31/kodi-alexa#201]
I've been attempting to follow the instructions on the guide as close as possible, an I feel like I've gotten most the steps down (as far as I can tell). However, after I run `zappa deploy dev` and I check the S3 bucket URL I see the following error: 

`"{u'message': u'An uncaught exception happened while servicing this request. You can investigate this with the `zappa tail` command.', u'traceback': ['Traceback (most recent call last):\\n', '  File \"/var/task/handler.py\", line 433, in handler\\n    response = Response.from_app(self.wsgi_app, environ)\\n', '  File \"/private/var/folders/lh/63cjfzbn31q8yhtrqn4jqnqc0000gp/T/pip-build-aWaFL5/Werkzeug/werkzeug/wrappers.py\", line 903, in from_app\\n', '  File \"/private/var/folders/lh/63cjfzbn31q8yhtrqn4jqnqc0000gp/T/pip-build-aWaFL5/Werkzeug/werkzeug/test.py\", line 884, in run_wsgi_app\\n', \"TypeError: 'NoneType' object is not callable\\n\"]}"`

From what I can see, Werkzeug is installed correctly, but I can't seem to find the origin of this error. I've tried re-installing venv and zappa, but it doesn't seem to work. Running the zappa tail I see some of the following logs: 

`[1499746900370] No module named packaging.version: ImportError
Traceback (most recent call last):
  File "/var/task/handler.py", line 490, in lambda_handler
  return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 240, in lambda_handler
  handler = cls()
  File "/var/task/handler.py", line 129, in __init__
  self.app_module = importlib.import_module(self.settings.APP_MODULE)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
  __import__(name)
  File "/var/task/alexa.py", line 14, in <module>
  from flask_ask import Ask, session, question, statement, audio, request, context
  File "/private/var/folders/lh/63cjfzbn31q8yhtrqn4jqnqc0000gp/T/pip-build-T0a3DA/flask-ask/flask_ask/__init__.py", line 9, in <module>
  File "/private/var/folders/lh/63cjfzbn31q8yhtrqn4jqnqc0000gp/T/pip-build-T0a3DA/flask-ask/flask_ask/core.py", line 12, in <module>
  File "/private/var/folders/lh/63cjfzbn31q8yhtrqn4jqnqc0000gp/T/pip-build-T0a3DA/flask-ask/flask_ask/verifier.py", line 8, in <module>
  File "/private/var/folders/lh/63cjfzbn31q8yhtrqn4jqnqc0000gp/T/pip-build-T0a3DA/pyOpenSSL/OpenSSL/__init__.py", line 8, in <module>
  File "/private/var/folders/lh/63cjfzbn31q8yhtrqn4jqnqc0000gp/T/pip-build-T0a3DA/pyOpenSSL/OpenSSL/crypto.py", line 13, in <module>
  File "/tmp/tmpIWCFLD/lib64/python/cryptography/hazmat/primitives/asymmetric/dsa.py", line 11, in <module>
  File "/tmp/tmpIWCFLD/lib64/python/cryptography/utils.py", line 13, in <module>
ImportError: No module named packaging.version`

and 

`[1499745059449] 'NoneType' object is not callable`

Alexa replies with "There was a problem with the requested skill response." The S3 bucket is active and all the Alex Skill configs look to be correct, but it seems like something in my python config isn't correct.

If I've missing something obvious, or missing important information for troubleshoot, please let me know. Thanks for your time.

**Comment by jingai** [comment]
You missed a step from [the README](https://github.com/m0ngr31/kodi-alexa#setup-1). In your virtualenv, you need to do `pip install packaging`.

**Comment by jpgamboa** [comment]
Yup. That did the trick. It is now deployed correctly and working. Thank you for the timely response.
