### ISSUE TITLE
Zappa step installation fails

### ISSUE THREAD

**Issue by kebogaer** [m0ngr31/kodi-alexa#229]
I get stuck on the zappa installation step ...
Installing on raspberry pi, Stretch OS.

When I try to install zappa, it reaches for lambda-pacakges-0.16.1, giving me the following error:

Collecting kappa==0.6.0 (from zappa)
Downloading kappa-0.6.0-py2-none-any.whl
Collecting lambda-packages==0.16.1 (from zappa)
Exception:
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
status = self.run(options, args)
File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 342, in run
requirement_set.prepare_files(finder)
File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
ignore_dependencies=self.ignore_dependencies))
File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
require_hashes
File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 278, in populate_link
self.link = finder.find_requirement(self, upgrade)
File "/usr/lib/python2.7/dist-packages/pip/index.py", line 465, in find_requirement
all_candidates = self.find_all_candidates(req.name)
File "/usr/lib/python2.7/dist-packages/pip/index.py", line 423, in find_all_candidates
for page in self._get_pages(url_locations, project_name):
File "/usr/lib/python2.7/dist-packages/pip/index.py", line 568, in _get_pages
page = self._get_page(location)
File "/usr/lib/python2.7/dist-packages/pip/index.py", line 683, in _get_page
return HTMLPage.get_page(link, session=self.session)
File "/usr/lib/python2.7/dist-packages/pip/index.py", line 795, in get_page
resp.raise_for_status()
File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/models.py", line 893, in raise_for_status
raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found for url: https://www.piwheels.hostedpi.com/simple/lambda-packages/

(venv) pi@raspberrypi:~/kodi-alexa $

What may be causing this?
I reported this at the Zappa github site, but got no response ...
perhaps I did not report it right, but I am a noob at this, so please bare with me

**Comment by jingai** [comment]
Basically, it's because you're doing it from an rPi, and `lambda-packages` doesn't appear to be available.  Just skip that package, I'd think.

**Comment by kebogaer** [comment]
But these packages are mandatory to upload code to AWS?

**Comment by jingai** [comment]
The packages in `requirements.txt` are mandatory, yes.  `lambda-packages` is a workaround to get `python-Levenshtein` up to AWS, but it will work without it.  In fact, on AWS, if I recall correctly, it was slower with it than without..

@m0ngr31 we should probably remove it from the docs?  Pretty sure it was slower for you with it?

**Comment by m0ngr31** [comment]
Try `pip uninstall python-Levenshtein` and `zappa deploy dev` again and see if that fixes it

**Comment by bennuttall** [comment]
Ok we discovered that there's a known bug in pip which breaks when additional indexes 404. The bug is still open in [pypa/pip](https://github.com/pypa/pip/issues/4605), and we can't expect a fix to find its way into Debian any time soon.

However, we ([piwheels](https://github.com/bennuttall/piwheels)) have mitigated this by creating empty directories for packages we haven't successfully built, which means pip gets an empty list of files rather than a 404 (which is an unhandled exception causing the fatal error).

Hopefully that means that this is no longer an issue here.

**Comment by jingai** [comment]
Thanks for the heads up @bennuttall !

**Comment by jingai** [comment]
@kebogaer is this working for you now?

**Comment by kebogaer** [comment]
Yes, zappa completes installation
thanks for the explanations
