### ISSUE TITLE
self hosted "wrong ELF class: ELFCLASS64" compatibility Raspberry pi?

### ISSUE THREAD

**Issue by ellisium** [m0ngr31/kodi-alexa#279]
Hello,

When running the command  on raspberry pi 3 b+: 
` gunicorn --certfile $CERT --keyfile $KEYFILE -b 0.0.0.0:8000 alexa:app`

I get the followinf error : 

`
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 557, in spawn_worker
    worker.init_process()
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 136, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python2.7/dist-packages/gunicorn/util.py", line 384, in import_app
    __import__(module)
  File "/home/pi/domotic/alexa/kanzi/kanzi/source/skill/alexa.py", line 17, in <module>
    from flask_ask import Ask, session, question, statement, audio, request, context
  File "/home/pi/domotic/alexa/kanzi/kanzi/source/skill/flask_ask/__init__.py", line 9, in <module>
    from .core import (
  File "/home/pi/domotic/alexa/kanzi/kanzi/source/skill/flask_ask/core.py", line 15, in <module>
    from . import verifier, logger
  File "/home/pi/domotic/alexa/kanzi/kanzi/source/skill/flask_ask/verifier.py", line 8, in <module>
    from OpenSSL import crypto
  File "/home/pi/domotic/alexa/kanzi/kanzi/source/skill/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/home/pi/domotic/alexa/kanzi/kanzi/source/skill/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/home/pi/domotic/alexa/kanzi/kanzi/source/skill/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/home/pi/domotic/alexa/kanzi/kanzi/source/skill/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /home/pi/domotic/alexa/kanzi/kanzi/source/skill/cryptography/hazmat/bindings/_openssl.so: wrong ELF class: ELFCLASS64
`

Should I understand this skill can run only on 64 bit system?

**Comment by ellisium** [comment]
I ran some pip unsintall + new git clone solved the issue. I had to install urllib3==1.23 manually but now no more error messages so I can continue working on self hosted solution. 

Edit:
I reopen it coz it's not working
