### ISSUE TITLE
SyntaxError: invalid syntax - Error when running deploy-to-lambda.py

### ISSUE THREAD

**Issue by scotscottmca** [m0ngr31/kodi-alexa#67]
Evening guys, 

Getting the error shown below when running "python deploy-to-lambda.py"

```
C:\Users\smcal\Desktop\kodi-alexa-master>python deploy-to-lambda.py
  File "deploy-to-lambda.py", line 34
    print subprocess.Popen("lambda-deploy deploy", shell=True, stdout=subprocess.PIPE).stdout.read()
                   ^
SyntaxError: invalid syntax
```

EDIT: Resolved my initial error, now getting the above

Can you shed any light on it/Point me in the right direction? 

Thanks

**Comment by digiltd** [comment]
Check your Python version, it doesn't work on Python 3.

See #51

**Comment by scotscottmca** [comment]
[Running Version 2.7 from what I can tell](http://imgur.com/a/MTZky)

**Comment by danielmasur** [comment]
C:\users\smcal\appdata\local\programs\python\python35-32

**Comment by scotscottmca** [comment]
Oh!, It would seem I have 2 versions installed. oops

**Comment by scotscottmca** [comment]
Ok that worked, Although I'm now back to my original error which is the following. 

`C:\Users\smcal\Desktop\kodi-alexa-master>python deploy-to-lambda.py
2016-11-22 17:49:45:INFO:botocore.vendored.requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): 169.254.169.254
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\lambda-deploy.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\lambda_deploy\lambda_deploy.py", line 360, in main
    name=options.name
  File "c:\python27\lib\site-packages\lambda_deploy\lambda_deploy.py", line 75, in __init__
    self.client = boto3.client('lambda')
  File "c:\python27\lib\site-packages\boto3\__init__.py", line 83, in client
    return _get_default_session().client(*args, **kwargs)
  File "c:\python27\lib\site-packages\boto3\session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "c:\python27\lib\site-packages\botocore\session.py", line 824, in create_client
    client_config=config, api_version=api_version)
  File "c:\python27\lib\site-packages\botocore\client.py", line 69, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "c:\python27\lib\site-packages\botocore\client.py", line 222, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "c:\python27\lib\site-packages\botocore\args.py", line 44, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "c:\python27\lib\site-packages\botocore\args.py", line 101, in compute_client_args
    service_name, region_name, endpoint_url, is_secure)
  File "c:\python27\lib\site-packages\botocore\client.py", line 295, in resolve
    service_name, region_name)
  File "c:\python27\lib\site-packages\botocore\regions.py", line 122, in construct_endpoint
    partition, service_name, region_name)
  File "c:\python27\lib\site-packages\botocore\regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.`

[Screenshot of the error](http://imgur.com/a/w1d7w)
[Screenshot of my .env file](http://imgur.com/a/PFx0z) - Wondering if I've named it properly? the original file is called .env.lambda, Although in the guide it says to copy this file so I'm assuming you give it a new name? in this case, alexa-kodi.env. 


I'm pretty new to all this, So any help you can provide would be amazing.

**Comment by jingai** [comment]
You need to name it .env

**Comment by scotscottmca** [comment]
Ahhh so like ".env.kodialexa" ?

**Comment by scotscottmca** [comment]
although does the fact im doing this in windows make any difference?

**Comment by m0ngr31** [comment]
No, Windows is fine. Filename needs to be `.env`.

**Comment by scotscottmca** [comment]
ok cool, So i get the following trying to name the file "`.env`" 

http://imgur.com/a/oLyQU

**Comment by m0ngr31** [comment]
Is that in Explorer or Notepad++?

**Comment by scotscottmca** [comment]
good catch, was in explorer. oops ha

**Comment by scotscottmca** [comment]
That worked m0ngr31, Thanks. 

Hopefully last question, 

`c:\Users\smcal\Desktop\kodi-alexa-master>python deploy-to-lambda.py
2016-11-22 19:24:02:INFO:botocore.credentials: Found credentials in environment variables.
2016-11-22 19:24:02:INFO:lambda_deploy: Packaging lambda kodi-alexa
2016-11-22 19:24:02:WARNING:lambda_deploy: A .env file exists in your Lambda directory - be careful that it does not contain any secrets you don't want uploaded to AWS!
2016-11-22 19:24:02:WARNING:lambda_deploy: Skipping inclusion of of .env file - use LAMBDA_ENV_VARS instead (see documentation for more information)
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\lambda-deploy.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\lambda_deploy\lambda_deploy.py", line 376, in main
    method()
  File "c:\python27\lib\site-packages\lambda_deploy\lambda_deploy.py", line 215, in deploy
    Publish=True
  File "c:\python27\lib\site-packages\botocore\client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "c:\python27\lib\site-packages\botocore\client.py", line 537, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: The role defined for the function cannot be assumed by Lambda.
Collecting requests (from -r c:\Users\smcal\Desktop\kodi-alexa-master\kodi-alexa\requirements.txt (line 1))
  Using cached requests-2.12.1-py2.py3-none-any.whl
Collecting gunicorn (from -r c:\Users\smcal\Desktop\kodi-alexa-master\kodi-alexa\requirements.txt (line 2))
  Using cached gunicorn-19.6.0-py2.py3-none-any.whl
Collecting yaep (from -r c:\Users\smcal\Desktop\kodi-alexa-master\kodi-alexa\requirements.txt (line 3))
  Using cached yaep-0.0.6-py2-none-any.whl
Collecting pycountry (from -r c:\Users\smcal\Desktop\kodi-alexa-master\kodi-alexa\requirements.txt (line 4))
Collecting pytz (from -r c:\Users\smcal\Desktop\kodi-alexa-master\kodi-alexa\requirements.txt (line 5))
  Using cached pytz-2016.7-py2.py3-none-any.whl
Collecting fuzzywuzzy (from -r c:\Users\smcal\Desktop\kodi-alexa-master\kodi-alexa\requirements.txt (line 6))
  Using cached fuzzywuzzy-0.14.0-py2.py3-none-any.whl
Installing collected packages: requests, gunicorn, yaep, pycountry, pytz, fuzzywuzzy
Successfully installed fuzzywuzzy-0.14.0 gunicorn-19.6.0 pycountry-16.11.8 pytz-2016.7 requests-2.12.1 yaep-0.0.6
Starting new HTTPS connection (1): lambda.eu-west-1.amazonaws.com
Adding new kodi-alexa lambda`

Completes with a few errors. . Seems to skip my .env file  
and
`botocore.exceptions.ClientError: An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: The role defined for the function cannot be assumed by Lambda.`

Suggestions?

**Comment by m0ngr31** [comment]
It's not skipping your `.env` file, it's just a message saying that it's not going to upload it to aws. The issue now seems to be that you need Lambda permissions on your role and user on AWS.

**Comment by scotscottmca** [comment]
Oh ok, I think i may have resolved it. 

Entirely new to Lambda and Echo, Throwing myself in at the deep end. 

thanks for your help
