### ISSUE TITLE
problems 

### ISSUE THREAD

**Issue by blairn64** [m0ngr31/kodi-alexa#87]
when i run  python deploy-to-lambda.py
2017-01-02 23:04:00:INFO:botocore.credentials: Found credentials in shared credentials file: ~/.aws/credentials
2017-01-02 23:04:00:ERROR:lambda_deploy: Missing AWS Role
2017-01-02 23:04:00:ERROR:lambda_deploy: Invalid arguments.

my .env file is:

KODI_ADDRESS = mykodiaddress
KODI_PORT =8080
KODI_USERNAME = myusername
KODI_PASSWORD = mypassword
LAMBDA_ENV_VARS = KODI_SCHEME,KODI_ADDRESS,KODI_PORT,KODI_SUBPATH,KODI_USERNAME,KODI_PASSWORD,SKILL_APPID,SKILL_TZ
[default]region = eu-west-1
AWS_DEFAULT_REGION = eu-west-1
LAMBDA_TIMEOUT = 60
LAMBDA_MEMORY_SIZE = 128
LAMBDA_HANDLER = wsgi.lambda_handler

AWS_ACCESS_KEY_ID = myaccesskey
AWS_SECRET_ACCESS_KEY = mysecretkey
LAMBDA_ROLE = my role

can anyone help?

**Comment by m0ngr31** [comment]
Did you make sure your AWS user has Lambda permissions?

**Comment by blairn64** [comment]
yeah i just re created another user and removed the old one in IAM management console i created a new user and granted full access to lambda in premissions and entered the details in the .env file  but still have the same issue when running deploy command

**Comment by m0ngr31** [comment]
Are you pasting in the ARN for your user on the LAMBDA_ROLE option?

**Comment by blairn64** [comment]
yeah iv pasted the LAMBDA_ROLE = arn:aws:iam::xxxxxxxxxxxx:role/lambda into the .env file

**Comment by m0ngr31** [comment]
Try and use your user ARN instead of the role one.

**Comment by digiltd** [comment]
It also looks like the .env file is not being read correctly and lambda-deploy is reading the aws-cli credentials instead.

In your first post you pasted your .env file as:

```
KODI_ADDRESS = mykodiaddress
KODI_PORT =8080
KODI_USERNAME = myusername
KODI_PASSWORD = mypassword
LAMBDA_ENV_VARS = KODI_SCHEME,KODI_ADDRESS,KODI_PORT,KODI_SUBPATH,KODI_USERNAME,KODI_PASSWORD,SKILL_APPID,SKILL_TZ
[default]region = eu-west-1
AWS_DEFAULT_REGION = eu-west-1
LAMBDA_TIMEOUT = 60
LAMBDA_MEMORY_SIZE = 128
LAMBDA_HANDLER = wsgi.lambda_handler

AWS_ACCESS_KEY_ID = myaccesskey
AWS_SECRET_ACCESS_KEY = mysecretkey
LAMBDA_ROLE = my role
```

Not sure if it was just a mistake when you copied and pasted it but `[default]region = eu-west-1` shouldn't be there.

**Comment by blairn64** [comment]
i changed the value of the LAMBDA_ROLE to the user ARN and the deploy runs but i now have  a different error  

botocore.exceptions.ClientError: An error occurred (InvalidSignatureException) when calling the CreateFunction operation: Signature expired: 20170104T142232Z is now earlier than 20170104T142539Z (20170104T143039Z - 5 min.)

iv pasted the command line here:


C:\Users\Blair\Downloads\kodi-alexa-master>C:\Python27\Scripts\lambda-deploy.exe deploy
2017-01-04 14:22:08:INFO:botocore.credentials: Found credentials in environment variables.
2017-01-04 14:22:09:INFO:lambda_deploy: Packaging lambda kodi-alexa-master
2017-01-04 14:22:09:WARNING:lambda_deploy: A .env file exists in your Lambda directory - be careful that it does not contain any secrets you don't want uploaded to AWS!
2017-01-04 14:22:09:WARNING:lambda_deploy: Skipping inclusion of of .env file - use LAMBDA_ENV_VARS instead (see documentation for more information)
2017-01-04 14:22:09:WARNING:lambda_deploy: Skipping inclusion of of .env file - use LAMBDA_ENV_VARS instead (see documentation for more information)
Collecting requests (from -r C:\Users\Blair\Downloads\kodi-alexa-master\requirements.txt (line 1))
  Using cached requests-2.12.4-py2.py3-none-any.whl
Collecting gunicorn (from -r C:\Users\Blair\Downloads\kodi-alexa-master\requirements.txt (line 2))
  Using cached gunicorn-19.6.0-py2.py3-none-any.whl
Collecting yaep (from -r C:\Users\Blair\Downloads\kodi-alexa-master\requirements.txt (line 3))
  Using cached yaep-0.0.6-py2-none-any.whl
Collecting pycountry (from -r C:\Users\Blair\Downloads\kodi-alexa-master\requirements.txt (line 4))
  Using cached pycountry-17.1.2.tar.gz
Collecting pytz (from -r C:\Users\Blair\Downloads\kodi-alexa-master\requirements.txt (line 5))
  Using cached pytz-2016.10-py2.py3-none-any.whl
                                  Collecting fuzzywuzzy (from -r C:\Users\Blair\Downloads\kodi-alexa-master\requirements.txt (line 6))
  Using cached fuzzywuzzy-0.14.0-py2.py3-none-any.whl
Installing collected packages: requests, gunicorn, yaep, pycountry, pytz, fuzzywuzzy
  Running setup.py install for pycountry ... done
Successfully installed fuzzywuzzy-0.14.0 gunicorn-19.6.0 pycountry-17.1.2 pytz-2016.10 requests-2.12.4 yaep-0.0.6
Starting new HTTPS connection (1): lambda.eu-west-1.amazonaws.com
Adding new kodi-alexa-master lambda
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\lambda-deploy.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\lambda_deploy\lambda_deploy.py", line 376, in main
    method()
  File "c:\python27\lib\site-packages\lambda_deploy\lambda_deploy.py", line 215, in deploy
    Publish=True
  File "c:\python27\lib\site-packages\botocore\client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "c:\python27\lib\site-packages\botocore\client.py", line 537, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidSignatureException) when calling the CreateFunction operation: Signature expired: 20170104T142232Z is now earlier than 20170104T142539Z (20170104T143039Z - 5 min.)

**Comment by m0ngr31** [comment]
Sounds like the same issue as this one: #69.

Looks like you just need to change your system clock to match.

**Comment by blairn64** [comment]
iv changed the system clock to match and get another error

C:\Users\Blair\Downloads\kodi-alexa-master>C:\Python27\Scripts\lambda-deploy.exe deploy
2017-01-04 19:22:11:INFO:botocore.credentials: Found credentials in environment variables.
2017-01-04 19:22:11:INFO:lambda_deploy: Packaging lambda kodi-alexa-master
2017-01-04 19:22:11:WARNING:lambda_deploy: A .env file exists in your Lambda directory - be careful that it does not contain any secrets you don't want uploaded to AWS!
2017-01-04 19:22:11:WARNING:lambda_deploy: Skipping inclusion of of .env file - use LAMBDA_ENV_VARS instead (see documentation for more information)
Collecting requests (from -r C:\Users\Blair\Downloads\kodi-alexa-master\requirements.txt (line 1))
  Using cached requests-2.12.4-py2.py3-none-any.whl
Collecting gunicorn (from -r C:\Users\Blair\Downloads\kodi-alexa-master\requirements.txt (line 2))
  Using cached gunicorn-19.6.0-py2.py3-none-any.whl
Collecting yaep (from -r C:\Users\Blair\Downloads\kodi-alexa-master\requirements.txt (line 3))
  Using cached yaep-0.0.6-py2-none-any.whl
Collecting pycountry (from -r C:\Users\Blair\Downloads\kodi-alexa-master\requirements.txt (line 4))
  Using cached pycountry-17.1.2.tar.gz
Collecting pytz (from -r C:\Users\Blair\Downloads\kodi-alexa-master\requirements.txt (line 5))
  Using cached pytz-2016.10-py2.py3-none-any.whl
Collecting fuzzywuzzy (from -r C:\Users\Blair\Downloads\kodi-alexa-master\requirements.txt (line 6))
  Using cached fuzzywuzzy-0.14.0-py2.py3-none-any.whl
Installing collected packages: requests, gunicorn, yaep, pycountry, pytz, fuzzywuzzy
  Running setup.py install for pycountry ... done
Successfully installed fuzzywuzzy-0.14.0 gunicorn-19.6.0 pycountry-17.1.2 pytz-2016.10 requests-2.12.4 yaep-0.0.6
Starting new HTTPS connection (1): lambda.eu-west-1.amazonaws.com
Adding new kodi-alexa-master lambda
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\lambda-deploy.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\lambda_deploy\lambda_deploy.py", line 376, in main
    method()
  File "c:\python27\lib\site-packages\lambda_deploy\lambda_deploy.py", line 215, in deploy
    Publish=True
  File "c:\python27\lib\site-packages\botocore\client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "c:\python27\lib\site-packages\botocore\client.py", line 537, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the CreateFunction operation: 1 validation error detected: Value 'arn:aws:iam::627098885616:user/blair' at 'role' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:aws:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+
