### ISSUE TITLE
Function Not Showing After Python Deploy To Lambda

### ISSUE THREAD

**Issue by noliebro** [m0ngr31/kodi-alexa#88]
Every other step worked fine while building this and I even moved ahead to create the Skills early and get the SKILL_APPID because it seems to ask for it in the env file. However, now I am not seeing any functions after using running the python commands in Terminal (Ubuntu 16.04). 

At first I was seeing this error:
```
File "/usr/local/lib/python2.7/dist-packages/botocore/regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
```
I made sure to change the region back to "us-east-1" as I had it as "us-west-1" and it seemed to move further through the process but now I get this alert:

```
:/kodi-alexa-master$ python deploy-to-lambda.py

Traceback (most recent call last):
  File "deploy-to-lambda.py", line 19, in <module>
    os.mkdir(app_name)
OSError: [Errno 17] File exists: 'kodi-alexa'
```
Checking the Lambda Management Console shows no Functions listed and I am not able to move forward.

**Comment by m0ngr31** [comment]
Delete the folder kodi-alexa and try running the command again.

**Comment by noliebro** [comment]
Thank you. Back to this error now 

`Starting new HTTP connection (1): 169.254.169.254
Traceback (most recent call last):
  File "/usr/local/bin/lambda-deploy", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/lambda_deploy/lambda_deploy.py", line 360, in main
    name=options.name
  File "/usr/local/lib/python2.7/dist-packages/lambda_deploy/lambda_deploy.py", line 75, in __init__
    self.client = boto3.client('lambda')
  File "/usr/local/lib/python2.7/dist-packages/boto3/__init__.py", line 83, in client
    return _get_default_session().client(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python2.7/dist-packages/botocore/session.py", line 828, in create_client
    client_config=config, api_version=api_version)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 69, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 222, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python2.7/dist-packages/botocore/args.py", line 44, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/usr/local/lib/python2.7/dist-packages/botocore/args.py", line 101, in compute_client_args
    service_name, region_name, endpoint_url, is_secure)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 295, in resolve
    service_name, region_name)
  File "/usr/local/lib/python2.7/dist-packages/botocore/regions.py", line 122, in construct_endpoint
    partition, service_name, region_name)
  File "/usr/local/lib/python2.7/dist-packages/botocore/regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
`

I have the region in the LAMBDA file so not sure why it is asking for the region:

`AWS_DEFAULT_REGION = us-east-1
LAMBDA_TIMEOUT = 60
LAMBDA_MEMORY_SIZE = 128
LAMBDA_HANDLER = wsgi.lambda_handler`

**Comment by digiltd** [comment]
What do you mean when you say "I have the region in the LAMBDA file"?

Are you using the .env file?

**Comment by jingai** [comment]
My guess is he/she didn't copy .env.lambda to .env before editing.  It seems Windows users frequently have trouble doing this, due to Windows wanting to 'correct' the filename.

**Comment by noliebro** [comment]
Sorry, my fault for working off a guide instead of using the README file. 

I never copied the files. I saved ".env.lamba" to ".env" and ran again and it seemed to work. 

However I did get this error in the middle. Is this something to worry about:

`WARNING:lambda_deploy: Skipping inclusion of of .env file - use LAMBDA_ENV_VARS instead (see documentation for more information)`

**Comment by jingai** [comment]
You can safely ignore that.  It's simply telling you that it's not going to upload the .env because that would be a security risk.
