### ISSUE TITLE
 An error occurred (InvalidSignatureException) when calling the CreateFunction operation

### ISSUE THREAD

**Issue by Loxitation** [m0ngr31/kodi-alexa#92]
Hey guys, I am currently trying to install Alexa with Kodi Voice Control, but I struggle since 2 days on one error. When I try to run 
`C:\Python27\Scripts\lambda-deploy.exe deploy`

it says

```
2017-01-05 21:51:58:INFO:botocore.credentials: Found credentials in environment variables.
2017-01-05 21:51:58:INFO:lambda_deploy: Packaging lambda kodi-alexa-master
2017-01-05 21:51:58:WARNING:lambda_deploy: A .env file exists in your Lambda directory - be careful that it does not contain any secrets you don't want uploaded to AWS!
2017-01-05 21:51:58:WARNING:lambda_deploy: Skipping inclusion of of .env file - use LAMBDA_ENV_VARS instead (see documentation for more information)
2017-01-05 21:51:58:WARNING:lambda_deploy: Skipping inclusion of of .env file - use LAMBDA_ENV_VARS instead (see documentation for more information)
Collecting requests (from -r C:\Users\u\Documents\kodi-alexa-master\requirements.txt (line 1))
  Using cached requests-2.12.4-py2.py3-none-any.whl
Collecting gunicorn (from -r C:\Users\u\Documents\kodi-alexa-master\requirements.txt (line 2))
  Using cached gunicorn-19.6.0-py2.py3-none-any.whl
Collecting yaep (from -r C:\Users\u\Documents\kodi-alexa-master\requirements.txt (line 3))
  Using cached yaep-0.0.6-py2-none-any.whl
Collecting pycountry (from -r C:\Users\u\Documents\kodi-alexa-master\requirements.txt (line 4))
  Using cached pycountry-17.1.2.tar.gz
Collecting pytz (from -r C:\Users\u\Documents\kodi-alexa-master\requirements.txt (line 5))
  Using cached pytz-2016.10-py2.py3-none-any.whl
Collecting fuzzywuzzy (from -r C:\Users\u\Documents\kodi-alexa-master\requirements.txt (line 6))
  Using cached fuzzywuzzy-0.14.0-py2.py3-none-any.whl
Installing collected packages: requests, gunicorn, yaep, pycountry, pytz, fuzzywuzzy
  Running setup.py install for pycountry ... done
Successfully installed fuzzywuzzy-0.14.0 gunicorn-19.6.0 pycountry-17.1.2 pytz-2016.10 requests-2.12.4 yaep-0.0.6
Starting new HTTPS connection (1): lambda.eu-west-1.amazonaws.com
Adding new kodi-alexa-master lambda
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\lambda-deploy.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\lambda_deploy\lambda_deploy.py", line 376, in main
    method()
  File "c:\python27\lib\site-packages\lambda_deploy\lambda_deploy.py", line 215, in deploy
    Publish=True
  File "c:\python27\lib\site-packages\botocore\client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "c:\python27\lib\site-packages\botocore\client.py", line 537, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidSignatureException) when calling the CreateFunction operation: Signature expired: 20170105T205220Z is now earlier than 20170105T205230Z (20170105T205730Z - 5 min.)

```

I dont know what to do about it, do you have any suggestions?

**Comment by m0ngr31** [comment]
Try adjusting your clock. It looks like it's 5 minutes off from Amazons server which is causing the issue.

**Comment by Loxitation** [comment]
Thanks for the reply, I will give it a try and reply.

**Comment by Loxitation** [comment]
So, it seems to work, thanks for your fast reply! :-) It is still saying "adding new kodi-alexa-master lambda", but that could be because of my slow internet conenction. On my AWS-Panel I could already see the kodi, but I woun't continue until my console tells me that it is ready. Will keep you up to date with the next information it gives to me :-)

**Comment by Loxitation** [comment]
Me again :D So the deploy seemed to work, but my Kodi does not react. Alexa says "Playback stopped", but the playback didnt. Any suggestions why this is happening?

**Comment by m0ngr31** [comment]
Curious if you have "trained" your voice for your device?

**Comment by m0ngr31** [comment]
And what other commands are you trying that aren't working?

**Comment by balaprasad18** [comment]
hello everyone, i need to cross check the atendance for the employee based on changing the date forward and back, but i am facing the same issue. Is it possible or not??  My assumption is when i checks in my system takes local time and date what i changed (eg: 3 days before from today), AWS will take current date and time. How to resolve this ??? 

botocore.exceptions.ClientError: An error occurred (InvalidSignatureException) when calling the CompareFaces operation: Signature expired: 20180707T233021Z is now earlier than 20180710T071214Z (20180710T071714Z - 5 min.)
